name: Build and deploy React app to Azure Web App - reactshop

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # React is stable on 18

      - name: npm install and build
        working-directory: react-order-client  # 👈 important!
        run: |
          npm install
          npm run build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: react-order-client/dist  # 👈 the React build output

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: react-build

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AD1B7981AB9D4B8FAE12C2A627F32AB0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B46A99AB310F4C27A8C93204DF38CDB5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_18C1581B08D6472F88EB69EA38632FD9 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'reactshop'
          slot-name: 'Production'
          package: .  # current folder contains the build
